name: C/C++ CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up CMake
      uses: lukka/get-cmake@v3.21.1

    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y ninja-build libcmocka-dev

    - name: Configure
      run: cmake -S . -B build -G Ninja

    - name: Build
      run: cmake --build build

    - name: Run tests
      run: ctest --test-dir build
